const express = require('express')
const router = express.Router()
const getController = require('../controllers/get.controllers')
const getControllerAvis = require('../controllers/get.controllers.reviews')
const getControllerAvisId = require('../controllers/get.controllers.reviews.id')
const postController = require('../controllers/post.controllers')
const postControllerRegister = require('../controllers/post.controllers.register')
const postControllerLogin = require('../controllers/post.controllers.login')
const postControllerForgotPassword = require('../controllers/post.controllers.forgot-password')
const postControllerResetPassword = require('../controllers/post.controllers.reset-password')
const putController = require('../controllers/put.controllers')
const deleteController = require('../controllers/delete.controllers')
const getMiddleware = require('../middleware/get.middleware')
const getMiddlewareReviews = require('../middleware/get.middleware.reviews')
const postMiddlewareRegister = require('../middleware/post.middleware.register')
const postMiddlewareLogin = require('../middleware/post.middleware.login')
const postMiddlewareForgotPassword = require('../middleware/post.middleware.forgot-password')
const postMiddlewareResetPassword = require('../middleware/post.middleware.reset-password')
const putMiddleware = require('../middleware/put.middleware')


router.get('/',getMiddleware, getController)
router.get('/avis', getMiddlewareReviews, getControllerAvis)
router.get('/avis/:id', getControllerAvisId)
router.post('/add/avis', postController)
router.put('/autoriser/avis/:id', putMiddleware, putController)
router.delete('/avis/:id', deleteController)
router.post('/register', postMiddlewareRegister)
router.post('/login', postMiddlewareLogin, postControllerLogin)
router.post('/change-password', putMiddleware)
router.post('/forgot-password', postMiddlewareForgotPassword, postControllerForgotPassword)
router.post('/reset-password', postMiddlewareResetPassword, postControllerResetPassword)

module.exports = router